server:
    port: 9093

spring:
    application:
      name: ou-hrms
    jpa:
      properties:
#        hibernate.show_sql: true
        hibernate.default-schema: ggh_vap
        hibernate:
            generate_statistics: false
            order_inserts: true
            jdbc:
                batch_size: 10
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ou_hrms
        password: postgres
        username: postgres
        hikari:
            connection-timeout: 30000
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            leak-detection-threshold: 1000
            pool-name: OUPOOL
            max-lifetime: 2000000
    kafka:
      bootstrap-servers: localhost:8097, localhost:8098, localhost:8099
      template:
        default-topic: ou-user-created
      properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
        ssl.endpoint.identification.algorithm:
      consumer:
        group-id: ou-hrms
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: "*"
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ou_hrms:
    topic:
      userCreated: ou-user-created
