kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraMounts:
    - hostPath: /home/atif/drive/mount
      containerPath: /data
  extraPortMappings:
    - containerPort: 30030
      hostPort: 80
    - containerPort: 30031
      hostPort: 81
    - containerPort: 30032
      hostPort: 82