server:
    port: 9095

spring:
    application:
      name: ou-notification
    jpa:
      properties:
#        hibernate.show_sql: true
        hibernate:
            generate_statistics: false
            order_inserts: true
            jdbc:
                batch_size: 10
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${DB_URL:jdbc:postgresql://localhost:5430/ou_notification}
        password: ${DB_PASSWORD:postgres}
        username: ${DB_USER:postgres}
        hikari:
            connection-timeout: 30000
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            leak-detection-threshold: 1000
            pool-name: OUPOOL
            max-lifetime: 2000000
    kafka:
      bootstrap-servers: localhost:8097, localhost:8098, localhost:8099
      properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
        ssl.endpoint.identification.algorithm:
      consumer:
        group-id: ou-notification
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: "*"
    mail:
      host: smtp.gmail.com
      port: 587
      username: 
      password: 
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com

            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ou_notification:
    topic:
      userCreated: ou-user-created
