spring:
  application:
    name: ou-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}