spring:
  application:
    name: ou-eureka

server:
  port: 8761

#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}
      
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/