server:
    port: 9090

spring:
    jpa:
      properties:
#        hibernate.show_sql: true
        hibernate.default-schema: ggh_vap
        hibernate:
            generate_statistics: false
            order_inserts: true
            jdbc:
                batch_size: 10
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ou_account
        password: postgres
        username: postgres
        hikari:
            connection-timeout: 30000
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            leak-detection-threshold: 1000
            pool-name: VAPPOOL
            max-lifetime: 2000000
            
ou_account:
    admin_role: ADMIN
