server:
    port: 9090

spring:
    application:
      name: ou-account
    jpa:
      properties:
#        hibernate.show_sql: true
        hibernate.default-schema: ggh_vap
        hibernate:
            generate_statistics: false
            order_inserts: true
            jdbc:
                batch_size: 10
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${DB_URL:jdbc:postgresql://localhost:5432/ou_account}
        password: ${DB_PASSWORD:postgres}
        username: ${DB_USER:postgres}
        hikari:
            connection-timeout: 30000
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            leak-detection-threshold: 1000
            pool-name: OUPOOL
            max-lifetime: 2000000
    kafka:
      bootstrap-servers: localhost:8097, localhost:8098, localhost:8099
      template:
        default-topic: ou-user-created
      properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
        ssl.endpoint.identification.algorithm:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/umbrella
        client:
          registration:
            keycloack:
              client-id: ou-clinet
              client-secret: 1hlB0MqynsDme1RBkS9IO7YrH4Onm8qY
              accessTokenUri: http://localhost:8080/realms/umbrella/protocol/openid-connect/token
 
logging:
  level:
    org:
      springframework:
        security: DEBUG
 
feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: basic 
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
            
ou_account:
    admin_role: ADMIN
    topic:
      userCreated: ou-user-created
